repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform.git
  rev: v1.97.4
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
      args: ['--args=--anchor=false', '--args=--hide resources,modules,data-sources']
    - id: terraform_tflint
      args: ['--args=--chdir=__GIT_WORKING_DIR__']
