{
 "title": "Debug Dashboard",
 "description": "this is for review and validate sections.\nRate Error [ Duration ] is used here",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "org",
    "label": "Organization",
    "query": {
     "query": "label_values(varnish_main_uptime,org)"
    }
   },
   {
    "name": "tier",
    "label": "Tier",
    "query": {
     "query": "label_values(varnish_main_uptime{org=~\"$org\"},tier)"
    }
   },
   {
    "name": "cache_node",
    "label": "Caching Node",
    "query": {
     "query": "label_values(varnish_main_cache{org=~\"$org\",tier=~\"$tier\"},host)"
    }
   },
   { "name": "_interval", "label": "Query Rate Interval", "query": "1m,5m,10m,30m" },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(varnish_backend_req,backend)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(increase(varnish_main_ws_client_overflow{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) + \nsum(increase(varnish_main_ws_backend_overflow{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) +\nsum(increase(varnish_main_ws_thread_overflow{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) +\nsum(increase(varnish_main_ws_session_overflow{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]) )",
     "legendFormat": "Workspace"
    },
    {
     "expr": "sum(increase(varnish_main_sc_rx_overflow{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) +\nsum(increase(varnish_main_sc_pipe_overflow{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))\n\n# SC overflow separated from other type of overflow",
     "legendFormat": "Session Close"
    },
    {
     "expr": "sum(increase(varnish_main_losthdr{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))\n# Header overflow separated from other type of overflow",
     "legendFormat": "Header"
    }
   ]
  },
  {
   "type": "stat",
   "description": "MAIN backend metric\n\nBackend Wait and Fail\n\nBackend Fetch Fail",
   "gridPos": { "h": 1, "w": 4, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(varnish_main_backend_fail{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) +\nsum(increase(varnish_main_backend_wait_fail{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Backend Fail"
    },
    {
     "expr": "sum(increase(varnish_main_fetch{type=~\"failed\",org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Fetch Fail"
    }
   ]
  },
  {
   "type": "stat",
   "description": "MAIN session close debug",
   "gridPos": { "h": 1, "w": 7, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(varnish_main_sc_tx_error{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Tx"
    },
    {
     "expr": "sum(increase(varnish_main_sc_rx_bad{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Rx"
    },
    {
     "expr": "sum(increase(varnish_main_sc_stream_failure{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Stream"
    },
    {
     "expr": "sum(increase(varnish_main_sc_rapid_reset{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Rreset"
    },
    {
     "expr": "sum(increase(varnish_main_sc_bankrupt{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "bankrupt"
    }
   ]
  },
  {
   "type": "stat",
   "description": "MAIN metric",
   "gridPos": { "h": 1, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(varnish_main_threads_failed{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Thread"
    },
    {
     "expr": "sum(increase(varnish_main_sessions{type=~\"fail.+\",org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Session"
    }
   ]
  },
  {
   "type": "stat",
   "description": "MAIN goto metric",
   "gridPos": { "h": 1, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(varnish_main_vcl_fail{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "VCL"
    },
    {
     "expr": "sum(increase(varnish_main_esi_errors{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "ESI"
    },
    {
     "expr": "sum(increase(varnish_sma_c_fail{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\",type=~\"s.+\"}[$__rate_interval]))",
     "legendFormat": "Malloc"
    }
   ]
  },
  {
   "title": "Cache HIT",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(varnish_main_cache_hit{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) / ignoring (type) group_left \nsum(rate(varnish_main_client_req{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Now"
    },
    {
     "expr": "max(sum(rate(varnish_main_cache_hit{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[12h])) / ignoring (type) group_left \nsum(rate(varnish_main_client_req{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[12h])))",
     "legendFormat": "12 hour max"
    },
    {
     "expr": "max(sum(rate(varnish_main_cache_hit{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[3d])) / ignoring (type) group_left \nsum(rate(varnish_main_client_req{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[3d])))",
     "legendFormat": "3 days max"
    }
   ]
  },
  {
   "title": "Traffic byte",
   "type": "stat",
   "description": "Current Network Usage\n\nMAIN metric request and response bytes",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(varnish_main_s_req_hdrbytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))\n\n# irate is used to get raw numbers on \"surges\" of bytes\n# used in transforming to \"ingress total\"",
     "legendFormat": "Req Header"
    },
    {
     "expr": "sum(irate(varnish_main_s_req_bodybytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))\n\n# used in transforming to \"ingress total\"",
     "legendFormat": "Req Body"
    },
    {
     "expr": "sum(irate(varnish_main_s_resp_hdrbytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))\n\n# used in transforming to \"egress total\"",
     "legendFormat": "Header"
    },
    {
     "expr": "sum(irate(varnish_main_s_resp_bodybytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))\n\n# used in transforming to \"egress total\"",
     "legendFormat": "Body"
    },
    {
     "expr": "sum(irate(varnish_main_s_pipe_hdrbytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Pipe Header"
    },
    {
     "expr": "sum(rate(varnish_main_s_req_hdrbytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) + \nsum(rate(varnish_main_s_req_bodybytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))\n\n# ingress bytes expected to be very minimal than egress (response) bytes",
     "legendFormat": "Ingress"
    },
    {
     "expr": "(sum(rate(varnish_main_s_resp_hdrbytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) by (host) + \n sum(rate(varnish_main_s_resp_bodybytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) by (host)) * 8\n\n# inverted graphs per host respose bytes",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(sum(rate(varnish_main_s_resp_hdrbytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) + \n sum(rate(varnish_main_s_resp_bodybytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))) * 8\n\n# hidden in view, used as positive numbers in legend. Total of response bytes in Y axis (not inverted)",
     "legendFormat": "Egress"
    }
   ]
  },
  {
   "title": "Request",
   "type": "stat",
   "description": "Rate of request seen",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(varnish_main_client_req{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Client"
    },
    {
     "expr": "sum(rate(varnish_backend_req{org=~\"$org\",tier=~\"$tier\",id!~\"cluster\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "title": "Request",
   "type": "stat",
   "description": "Derived rate of request seen per session",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(varnish_main_req_dropped{org=~\"$org\",tier=~\"$tier\"}[$__rate_interval])) ",
     "legendFormat": "Dropped"
    },
    {
     "expr": "sum(rate(varnish_main_req_reset{org=~\"$org\",tier=~\"$tier\"}[$__rate_interval])) ",
     "legendFormat": "Reset"
    }
   ]
  },
  {
   "title": "Cache Eviction",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(increase(varnish_main_n_obj_purged{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Purge"
    },
    {
     "expr": "sum(increase(varnish_main_bans{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "BAN"
    },
    {
     "expr": "sum(increase(varnish_main_n_lru_nuked{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "LRU"
    }
   ]
  },
  {
   "title": "VCL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(varnish_main_n_vcl_avail{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Backend",
   "type": "stat",
   "description": "\n\nHigher is better, meaning connection is reused\n\nExclude cluster,default,goto",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(varnish_main_backend_retry{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Retry"
    },
    {
     "expr": "sum(rate(varnish_main_backend_wait{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Wait"
    }
   ]
  },
  {
   "title": "object",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(varnish_main_beresp_shortlived{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "shortlived"
    }
   ]
  },
  {
   "title": "SHM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(varnish_main_shm_flushes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Flush"
    }
   ]
  },
  {
   "title": "ESI",
   "type": "stat",
   "description": "Rate of esi request",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(varnish_main_esi_req{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "gzip /gunzip rate"
    }
   ]
  },
  {
   "title": "Probe",
   "type": "stat",
   "description": "Thread queue length",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(resets(varnish_backend_happy{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Fail"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Cache hit, hit_grace, hitmiss, hitpass VS synth, pass",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": " # varnish-cache hit\n    (\n        sum(rate(varnish_main_cache_hit{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))\n    )\n\n/\nsum(rate(varnish_main_client_req{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) ",
     "legendFormat": "hit"
    },
    {
     "expr": " # varnish-cache hitmiss\n    (\n        sum(rate(varnish_main_cache_hitmiss{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))\n    )\n\n/\nsum(rate(varnish_main_client_req{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) ",
     "legendFormat": "hitmiss"
    },
    {
     "expr": " # varnish-cache hitpass\n    (\n        sum(rate(varnish_main_cache_hitpass{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))\n    )\n\n/\nsum(rate(varnish_main_client_req{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) ",
     "legendFormat": "hitpass"
    },
    {
     "expr": "sum(rate(varnish_main_s_synth{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) /\nsum(rate(varnish_main_client_req{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))\n\n# Synth usage may be higher depends on VCL. This must not be included when trying to account for 100% of client requests",
     "legendFormat": "synth"
    },
    {
     "expr": "sum(rate(varnish_main_s_pass{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) /\nsum(rate(varnish_main_client_req{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "pass"
    }
   ]
  },
  {
   "title": "Backend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backend [Main]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(varnish_backend_busy{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "busy"
      },
      {
       "expr": "sum(rate(varnish_backend_conn{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "conn"
      },
      {
       "expr": "sum(rate(varnish_backend_reuse{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "reuse"
      },
      {
       "expr": "sum(rate(varnish_backend_unhealthy{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "unhealthy"
      },
      {
       "expr": "sum(rate(varnish_backend_fail{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "fail"
      },
      {
       "expr": "sum(rate(varnish_backend_recycle{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "recycle"
      },
      {
       "expr": "sum(rate(varnish_backend_retry{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "retry"
      },
      {
       "expr": "sum(rate(varnish_backend_wait{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "wait"
      },
      {
       "expr": "sum(rate(varnish_backend_wait_fail{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "wait_fail"
      }
     ]
    },
    {
     "title": "Connection State [Main]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(varnish_main_backend_conn{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "Connection(All good)"
      },
      {
       "expr": "sum(rate(varnish_main_backend_busy{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "busy"
      },
      {
       "expr": "sum(rate(varnish_main_backend_fail{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "fail"
      },
      {
       "expr": "sum(rate(varnish_main_backend_reuse{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "reuse"
      },
      {
       "expr": "sum(rate(varnish_main_backend_recycle{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "recycle"
      },
      {
       "expr": "sum(rate(varnish_main_backend_retry{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "retry"
      },
      {
       "expr": "sum(rate(varnish_main_backend_wait{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "wait"
      },
      {
       "expr": "sum(rate(varnish_main_backend_wait_fail{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "wait_fail"
      }
     ]
    },
    {
     "title": "Backend bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(varnish_backend_bereq_hdrbytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\",backend=~\"$backend\"}[$__rate_interval])) by (backend)",
       "legendFormat": "request header-{{backend}}"
      },
      {
       "expr": "sum(rate(varnish_backend_bereq_bodybytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\",backend=~\"$backend\"}[$__rate_interval])) by (backend)",
       "legendFormat": "request body-{{backend}}"
      },
      {
       "expr": "sum(rate(varnish_backend_beresp_hdrbytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\",backend=~\"$backend\"}[$__rate_interval])) by (backend)",
       "legendFormat": "response header-{{backend}}"
      },
      {
       "expr": "sum(rate(varnish_backend_beresp_bodybytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\",backend=~\"$backend\"}[$__rate_interval])) by (backend)",
       "legendFormat": "response body-{{backend}}"
      }
     ]
    },
    {
     "title": "Fail Reasons",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(varnish_backend_fail_eacces{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\",backend=~\"$backend\"}[$__rate_interval])) by (backend)",
       "legendFormat": "eaccess-{{backend}}"
      },
      {
       "expr": "sum(rate(varnish_backend_fail_eaddrnotavail{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\",backend=~\"$backend\"}[$__rate_interval])) by (backend)",
       "legendFormat": "eaddrnotavail-{{backend}}"
      },
      {
       "expr": "sum(rate(varnish_backend_fail_econnrefused{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\",backend=~\"$backend\"}[$__rate_interval])) by (backend)",
       "legendFormat": "econnrefused-{{backend}}"
      },
      {
       "expr": "sum(rate(varnish_backend_fail_enetunreach{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\",backend=~\"$backend\"}[$__rate_interval])) by (backend)",
       "legendFormat": "enetunreach-{{backend}}"
      },
      {
       "expr": "sum(rate(varnish_backend_fail_etimedout{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\",backend=~\"$backend\"}[$__rate_interval])) by (backend)",
       "legendFormat": "etimedout-{{backend}}"
      },
      {
       "expr": "sum(rate(varnish_backend_fail_other{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\",backend=~\"$backend\"}[$__rate_interval])) by (backend)",
       "legendFormat": "other-{{backend}}"
      },
      {
       "expr": "sum(rate(varnish_backend_helddown{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\",backend=~\"$backend\"}[$__rate_interval])) by (backend)",
       "legendFormat": "helddown-{{backend}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Lock",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Locks created",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(varnish_lock_created{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) by (target)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Locks busy",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(varnish_lck_dbg_busy{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) by (id)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Locks trylock",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(varnish_lck_dbg_try_fail{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) by (id)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Session",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "\nsum(rate(varnish_main_sessions{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\",type!~\"fail.*\"}[$__rate_interval])) by (type)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Fail Reasons",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "\nsum(rate(varnish_main_sessions{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\",type=~\"fail.*\"}[$__rate_interval])) by (type)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Closed with error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(varnish_main_sc_bankrupt{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "bankrupt"
      },
      {
       "expr": "sum(rate(varnish_main_sc_rapid_reset{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "rapid_reset"
      },
      {
       "expr": "sum(rate(varnish_main_sc_vcl_failure{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "vcl_failure"
      },
      {
       "expr": "sum(rate(varnish_main_sc_req_http20{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "req_http20"
      },
      {
       "expr": "sum(rate(varnish_main_sc_range_short{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "range_short"
      },
      {
       "expr": "sum(rate(varnish_main_sc_pipe_overflow{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "pipe_overflow"
      },
      {
       "expr": "sum(rate(varnish_main_sc_overload{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "overload"
      },
      {
       "expr": "sum(rate(varnish_main_sc_tx_error{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "tx_error"
      },
      {
       "expr": "sum(rate(varnish_main_sc_rx_close_idle{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "rx_close_idle"
      },
      {
       "expr": "sum(rate(varnish_main_sc_rx_timeout{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))\n\n# may be seen as normal behavior for some application",
       "legendFormat": "rx_timeout"
      },
      {
       "expr": "sum(rate(varnish_main_sc_rx_overflow{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "rx_overflow"
      },
      {
       "expr": "sum(rate(varnish_main_sc_rx_junk{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "rx_junk"
      },
      {
       "expr": "sum(rate(varnish_main_sc_rx_body{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "rx_body"
      },
      {
       "expr": "sum(rate(varnish_main_sc_rx_bad{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "rx_bad"
      },
      {
       "expr": "sum(rate(varnish_main_sc_req_http10{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "req_http10"
      }
     ]
    }
   ]
  },
  {
   "title": "Mempool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mempool size requested - allocated",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(varnish_mempool_sz_wanted{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}) by (id) -\nsum(varnish_mempool_sz_actual{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}) by (id)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mempool frees / allocations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(varnish_mempool_frees{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}) by (id) /\nsum(varnish_mempool_allocs{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}) by (id)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mempool timeout / recycle",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(varnish_mempool_timeout{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) by (id,host) / \nsum(rate(varnish_mempool_recycle{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) by (id,host)",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Mempool others",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(varnish_mempool_toosmall{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) by (id,host)",
       "legendFormat": "toosmall-{{id}},{{host}}"
      },
      {
       "expr": "sum(rate(varnish_mempool_surplus{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) by (id,host)",
       "legendFormat": "surplus-{{id}},{{host}}"
      },
      {
       "expr": "sum(rate(varnish_mempool_randry{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) by (id,host)",
       "legendFormat": "randry-{{id}},{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Malloc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Malloc Size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(varnish_sma_g_space{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}) by (type,host) + \nsum(varnish_sma_g_bytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}) by (type,host)",
       "legendFormat": "malloc-{{type}},{{host}}"
      }
     ]
    },
    {
     "title": "SMA allocated and freed",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 9, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(varnish_sma_c_bytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) by (type)",
       "legendFormat": "{{type}}-allocation"
      },
      {
       "expr": "sum(rate(varnish_sma_c_freed{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) by (type)",
       "legendFormat": "{{type}}-freed"
      }
     ]
    },
    {
     "title": "SMA requests and failures",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(varnish_sma_c_req{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) by (type)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(increase(varnish_sma_c_fail{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) by (type)",
       "legendFormat": "fail-{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Fetch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fetch",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(varnish_main_s_bgfetch{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "background"
      },
      {
       "expr": "sum(rate(varnish_main_fetch_total{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
       "legendFormat": "Initiated"
      }
     ]
    },
    {
     "title": "Type",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 15, "x": 9, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(varnish_main_fetch{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  }
 ]
}