{
 "title": "Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "org",
    "label": "Organization",
    "query": {
     "query": "label_values(varnish_main_uptime,org)"
    }
   },
   {
    "name": "tier",
    "label": "Tier",
    "query": {
     "query": "label_values(varnish_main_uptime{org=~\"$org\"},tier)"
    }
   },
   {
    "name": "cache_node",
    "label": "Caching Node",
    "query": {
     "query": "label_values(varnish_main_cache{org=~\"$org\",tier=~\"$tier\"},host)"
    }
   },
   { "name": "_interval", "label": "Query Rate Interval", "query": "1m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(increase(varnish_main_ws_client_overflow{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) + \nsum(increase(varnish_main_ws_backend_overflow{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) +\nsum(increase(varnish_main_ws_thread_overflow{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) +\nsum(increase(varnish_main_ws_session_overflow{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]) )",
     "legendFormat": "Workspace"
    },
    {
     "expr": "sum(increase(varnish_main_sc_rx_overflow{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) +\nsum(increase(varnish_main_sc_pipe_overflow{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))\n\n# SC overflow separated from other type of overflow",
     "legendFormat": "Session Close"
    },
    {
     "expr": "sum(increase(varnish_main_losthdr{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))\n# Header overflow separated from other type of overflow",
     "legendFormat": "Header"
    }
   ]
  },
  {
   "type": "stat",
   "description": "MAIN backend metric\n\nBackend Wait and Fail\n\nBackend Fetch Fail",
   "gridPos": { "h": 1, "w": 4, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(varnish_main_backend_fail{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) +\nsum(increase(varnish_main_backend_wait_fail{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Backend Fail"
    },
    {
     "expr": "sum(increase(varnish_main_fetch{type=~\"failed\",org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Fetch Fail"
    }
   ]
  },
  {
   "type": "stat",
   "description": "MAIN session close debug",
   "gridPos": { "h": 1, "w": 7, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(varnish_main_sc_tx_error{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Tx"
    },
    {
     "expr": "sum(increase(varnish_main_sc_rx_bad{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Rx"
    },
    {
     "expr": "sum(increase(varnish_main_sc_stream_failure{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Stream"
    },
    {
     "expr": "sum(increase(varnish_main_sc_rapid_reset{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Rreset"
    },
    {
     "expr": "sum(increase(varnish_main_sc_bankrupt{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "bankrupt"
    }
   ]
  },
  {
   "type": "stat",
   "description": "MAIN metric",
   "gridPos": { "h": 1, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(varnish_main_threads_failed{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Thread"
    },
    {
     "expr": "sum(increase(varnish_main_sessions{type=~\"fail.+\",org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Session"
    }
   ]
  },
  {
   "type": "stat",
   "description": "MAIN goto metric",
   "gridPos": { "h": 1, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(varnish_main_vcl_fail{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "VCL"
    },
    {
     "expr": "sum(increase(varnish_main_esi_errors{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "ESI"
    },
    {
     "expr": "sum(increase(varnish_sma_c_fail{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\",type=~\"s.+\"}[$__rate_interval]))",
     "legendFormat": "Malloc"
    }
   ]
  },
  {
   "title": "Cache HIT",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(varnish_main_cache_hit{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) / ignoring (type) group_left \nsum(rate(varnish_main_client_req{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))\n",
     "legendFormat": "Now"
    },
    {
     "expr": "max(sum(rate(varnish_main_cache_hit{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[12h])) / ignoring (type) group_left \nsum(rate(varnish_main_client_req{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[12h])))",
     "legendFormat": "12 hour max"
    },
    {
     "expr": "max(sum(rate(varnish_main_cache_hit{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[3d])) / ignoring (type) group_left \nsum(rate(varnish_main_client_req{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[3d])))",
     "legendFormat": "3 days max"
    }
   ]
  },
  {
   "title": "Traffic byte",
   "type": "stat",
   "description": "Current Network Usage\n\nMAIN metric request and response bytes",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "panelId": 112 }
   ]
  },
  {
   "title": "Request",
   "type": "stat",
   "description": "Rate of request seen",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(varnish_main_client_req{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Client"
    },
    {
     "expr": "sum(rate(varnish_backend_req{org=~\"$org\",tier=~\"$tier\",id!~\"cluster\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "title": "Client Request/Session",
   "type": "stat",
   "description": "Derived rate of request seen per session",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(varnish_main_client_req{org=~\"$org\",tier=~\"$tier\"}[$__rate_interval])) / \nsum(rate(varnish_main_sessions{type=~\"conn\",org=~\"$org\",tier=~\"$tier\"}[$__rate_interval]))",
     "legendFormat": "Client Request / Session"
    }
   ]
  },
  {
   "title": "Purge",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(increase(varnish_main_n_obj_purged{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Cache"
    },
    {
     "expr": "sum(increase(varnish_main_bans{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "BAN"
    }
   ]
  },
  {
   "title": "VMOD count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(varnish_main_vmods{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"})",
     "legendFormat": "import"
    }
   ]
  },
  {
   "title": "Backend Connection/Reuse",
   "type": "stat",
   "description": "Derived rate of backend request per connection\n\nHigher is better, meaning connection is reused\n\nExclude cluster,default,goto",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    sum(rate(varnish_backend_req{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) +\n    sum(rate(varnish_main_s_pass{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) +\n    sum(rate(varnish_main_s_pipe{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) \n    )\n/\nsum(rate(varnish_backend_conn{org=~\"$org\",tier=~\"$tier\",id!~\"cluster|default|goto\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Backend Connection / Reuse"
    }
   ]
  },
  {
   "title": "Object core/head",
   "type": "stat",
   "description": "object-core in comparison to object-head count \n",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(varnish_main_n_objectcore{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) / \nsum(rate(varnish_main_n_objecthead{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Object Variation Rate"
    }
   ]
  },
  {
   "title": "gzip / gunzip",
   "type": "stat",
   "description": "Compression / decompression",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(varnish_main_n_gzip{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) / \nsum(rate(varnish_main_n_gunzip{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "gzip /gunzip rate"
    }
   ]
  },
  {
   "title": "ESI",
   "type": "stat",
   "description": "Rate of esi request",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(varnish_main_esi_req{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "gzip /gunzip rate"
    }
   ]
  },
  {
   "title": "Thread Queue",
   "type": "stat",
   "description": "Thread queue length",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(irate(varnish_main_thread_queue_len{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Thread Queue"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Cache hit, hit_grace, hitmiss, hitpass VS synth, pass",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": " # varnish-cache hit\n    (\n        sum(rate(varnish_main_cache_hit{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))\n    )\n\n/\nsum(rate(varnish_main_client_req{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) ",
     "legendFormat": "hit"
    },
    {
     "expr": " # varnish-cache hitmiss\n    (\n        sum(rate(varnish_main_cache_hitmiss{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))\n    )\n\n/\nsum(rate(varnish_main_client_req{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) ",
     "legendFormat": "hitmiss"
    },
    {
     "expr": " # varnish-cache hitpass\n    (\n        sum(rate(varnish_main_cache_hitpass{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))\n    )\n\n/\nsum(rate(varnish_main_client_req{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) ",
     "legendFormat": "hitpass"
    },
    {
     "expr": "sum(rate(varnish_main_s_synth{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) /\nsum(rate(varnish_main_client_req{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))\n\n# Synth usage may be higher depends on VCL. This must not be included when trying to account for 100% of client requests",
     "legendFormat": "synth"
    },
    {
     "expr": "sum(rate(varnish_main_s_pass{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) /\nsum(rate(varnish_main_client_req{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "pass"
    }
   ]
  },
  { "title": "Resource Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(varnish_main_s_req_hdrbytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))\n\n# irate is used to get raw numbers on \"surges\" of bytes",
     "legendFormat": "Req Header"
    },
    {
     "expr": "sum(irate(varnish_main_s_req_bodybytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Req Body"
    },
    {
     "expr": "sum(irate(varnish_main_s_resp_hdrbytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Header"
    },
    {
     "expr": "sum(irate(varnish_main_s_resp_bodybytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Body"
    },
    {
     "expr": "sum(irate(varnish_main_s_pipe_hdrbytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))",
     "legendFormat": "Pipe Header"
    },
    {
     "expr": "sum(rate(varnish_main_s_req_hdrbytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) + \nsum(rate(varnish_main_s_req_bodybytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))\n\n# ingress bytes expected to be very minimal than egress (response) bytes",
     "legendFormat": "Ingress"
    },
    {
     "expr": "(sum(rate(varnish_main_s_resp_hdrbytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) by (host) + \n sum(rate(varnish_main_s_resp_bodybytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) by (host)) * 8\n\n# inverted graphs per host respose bytes",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(sum(rate(varnish_main_s_resp_hdrbytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) + \n sum(rate(varnish_main_s_resp_bodybytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))) * 8\n\n# hidden in view, used as positive numbers in legend. Total of response bytes in Y axis (not inverted)",
     "legendFormat": "Egress"
    }
   ]
  },
  {
   "title": "Header vs Body bytes",
   "type": "timeseries",
   "description": "Network Payload\n\nDerived from other panel",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    { "panelId": 112 }
   ]
  },
  {
   "title": "Cache Memory Usage",
   "type": "timeseries",
   "description": "Bars: RSS size\n\nLine: Allocated and freed Resources",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(varnish_sma_g_space{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\",type=~\"s.+\"}) by (host) + \nsum(varnish_sma_g_bytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\",type=~\"s.+\"}) by (host)",
     "legendFormat": "RSS {{host}}"
    },
    {
     "expr": "sum(rate(varnish_sma_g_bytes{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\",type=~\"s.+\"}[$__rate_interval])) by (host)",
     "legendFormat": "Allocated"
    },
    {
     "expr": "sum(rate(varnish_sma_c_freed{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\",type=~\"s.+\"}[$__rate_interval])) by (host)",
     "legendFormat": "Freed"
    }
   ]
  },
  {
   "title": "HTTP Request vs Backend",
   "type": "timeseries",
   "description": "Client request vs backend requests\n\nBars: Backend request count\n\nLine: Host client request count",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(varnish_main_client_req{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) by (host)",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "sum(increase(varnish_backend_req{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) by (backend)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Object Fill",
   "type": "timeseries",
   "description": "Delta objects, showing differences of objects from previous point in time\n\nAlso showing increase removal by purging, nuking, or expiring objects\n\nSolid lines: Host object count\nDots: Count of removed objects",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(varnish_main_n_object{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) by (host)\n\n# changes in cache object per host",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "sum(increase(varnish_main_n_expired{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))\n\n# expired entries from cache",
     "legendFormat": "Expired"
    },
    {
     "expr": "sum(increase(varnish_main_n_lru_nuked{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval])) + \nsum(increase(varnish_main_n_obj_purged{org=~\"$org\",tier=~\"$tier\",host=~\"$cache_node\"}[$__rate_interval]))\n\n# nuked andor removed from cache",
     "legendFormat": "Removed"
    }
   ]
  }
 ]
}