{
 "title": "Varnish Cache metrics",
 "description": "A dashboard to use to debug a running varnish instance. Easily track requests, cache hits, network i/o, sessions, threads, bans, ban lurker and the ban list size",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(varnish_client_duration_total_seconds_bucket,service_name)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(varnish_client_duration_total_seconds_bucket{service_name=~\"$service\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Varnish instances",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(varnish_uptime{service_name=~\"$service\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Serving",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(varnish_client_response_bytes_byte_sum{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Serving",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((rate(varnish_client_duration_total_seconds_count{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "Requests/sec"
    }
   ]
  },
  {
   "title": "Traffic offload (requests)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum(rate(varnish_backend_duration_total_seconds_count{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval])) / sum(rate(varnish_client_duration_total_seconds_count{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Traffic offload (bytes)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum(rate(varnish_backend_response_bytes_byte_sum{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval])) / (sum(rate(varnish_client_response_bytes_byte_sum{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))))",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Panics recorded",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(varnish_child_panics{service_name=~\"$service\",instance=~\"$instance\"})",
     "legendFormat": "MGT uptime"
    }
   ]
  },
  {
   "title": "Data transfer per second",
   "type": "timeseries",
   "description": "Data transfer per second, which consists of headers and body bytes in the backend requests and backend responses.",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(varnish_client_response_bytes_byte_sum{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Client response"
    },
    {
     "expr": "sum(rate(varnish_backend_request_bytes_byte_sum{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Backend request"
    },
    {
     "expr": "sum(rate(varnish_client_request_bytes_byte_sum{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Client request"
    },
    {
     "expr": "sum(rate(varnish_backend_response_bytes_byte_sum{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Backend response"
    }
   ]
  },
  {
   "title": "New connections and requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(varnish_main_backend_connections{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Backend connections"
    },
    {
     "expr": "sum(rate(varnish_main_sess{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Client connections"
    },
    {
     "expr": "sum(rate(varnish_backend_requests{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Backend requests"
    },
    {
     "expr": "sum(rate(varnish_main_client_requests{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Client requests"
    }
   ]
  },
  {
   "title": "Offload rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (sum(rate(varnish_backend_duration_total_seconds_count{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval])) / sum(rate(varnish_client_duration_total_seconds_count{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "Requests"
    },
    {
     "expr": "1 - sum(rate(varnish_main_backend_connections{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval])) / sum(rate(varnish_main_sess{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Connections"
    },
    {
     "expr": "1 - (sum(rate(varnish_backend_response_bytes_byte_sum{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval])) / sum(rate(varnish_client_response_bytes_byte_sum{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "Bytes"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Response Sizes",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(increase(varnish_client_response_bytes_byte_bucket{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Session failures",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (failure_type) (rate(varnish_main_session_failed{service_name=~\"$service\",instance=~\"$instance\",failure_type!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{failure_type}}"
    }
   ]
  },
  {
   "title": "Cache invalidation requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(varnish_main_purges{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Number of purge operations executed"
    },
    {
     "expr": "sum(rate(varnish_main_bans{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Active Bans"
    },
    {
     "expr": "sum(rate(varnish_main_ban_req{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Lurker-unfriendly bans"
    }
   ]
  },
  {
   "title": "Objects invalidated",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(varnish_mse4_book_ykey_purged{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Number of objects purged with YKey"
    },
    {
     "expr": "sum(rate(varnish_mse4_book_ykey_slicer_purged{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Number of slicer objects purged with YKey (MSE4)"
    },
    {
     "expr": "sum(rate(varnish_main_obj_purged{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Number of purged objects"
    },
    {
     "expr": "sum(rate(varnish_main_ban_obj_killed{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Objects killed by bans (lookup)"
    },
    {
     "expr": "sum(rate(varnish_main_ban_lurker_obj_killed{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Objects killed by bans (lurker)"
    },
    {
     "expr": "sum(rate(varnish_main_ban_lurker_obj_killed_cutoff{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Objects killed by bans for cutoff (lurker)"
    },
    {
     "expr": "rate(varnish_mse3_store_ykey_purged{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Number of slicer objects purged with YKey (MSE3)"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "ESI subrequests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(varnish_main_esi_requests{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Backend errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (failure_type) (rate(varnish_backend_failed{service_name=~\"$service\",instance=~\"$instance\", failure_type!=\"\"}[$__rate_interval]))",
     "legendFormat": "Fetch failed ({{failure_type}})"
    },
    {
     "expr": "sum(rate(varnish_main_backend_wait_failed{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Backend conn. waited in queue and did not get a connection"
    },
    {
     "expr": "sum(rate(varnish_main_bgfetch_no_thread{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Background fetch failed (no thread)"
    }
   ]
  },
  {
   "title": "Various errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(varnish_main_client_req_417{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Client requests received, subject to 417 errors"
    },
    {
     "expr": "sum(rate(varnish_main_vdp_error{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Session Err VDP_FAILURE"
    },
    {
     "expr": "sum(rate(varnish_main_stream_failure{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Session Err VDP_ERROR_FETCH"
    },
    {
     "expr": "sum(rate(varnish_main_rapid_reset{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Session Err RAPID_RESET"
    },
    {
     "expr": "sum(rate(varnish_main_esi_errors{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "ESI parse errors"
    },
    {
     "expr": "sum(rate(varnish_main_ws_backend_overflow{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "workspace_backend overflows"
    },
    {
     "expr": "sum(rate(varnish_main_ws_client_overflow{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "workspace_client overflows"
    },
    {
     "expr": "sum(rate(varnish_main_thread_thread_overflow{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "workspace_thread overflows"
    },
    {
     "expr": "sum(rate(varnish_main_ws_session_overflow{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "workspace_session overflows"
    },
    {
     "expr": "sum(rate(varnish_main_vcl_fail{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "VCL failures"
    },
    {
     "expr": "sum(rate(varnish_main_lru_limited{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Reached nuke_limit"
    },
    {
     "expr": "sum(rate(varnish_varnish_main_losthdr{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "HTTP header overflows"
    },
    {
     "expr": "sum(rate(varnish_main_vcl_failure{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Session Err VCL_FAILURE"
    },
    {
     "expr": "sum(rate(varnish_main_thread_limited{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Threads hit max"
    },
    {
     "expr": "sum(rate(varnish_main_thread_failed{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Thread creation failed"
    },
    {
     "expr": "sum(rate(varnish_main_task_track_failed{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Failed to track a task"
    },
    {
     "expr": "sum(rate(varnish_main_session_dropped{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Sessions dropped for thread"
    },
    {
     "expr": "sum(rate(varnish_main_request_dropped{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Requests dropped"
    },
    {
     "expr": "sum(rate(varnish_main_goto_dns_lookup_fails{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Number of unresolved DNS lookups from vmod_goto's DNS"
    },
    {
     "expr": "sum(rate(varnish_main_vgs_msg_nospace{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Gravestone message insufficient space"
    },
    {
     "expr": "sum(rate(varnish_child_panics{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Child process panics"
    },
    {
     "expr": "sum(rate(varnish_main_client_req_400{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Client requests received, subject to 400 errors"
    },
    {
     "expr": "sum(rate(varnish_main_client_resp_500{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Delivery failed due to insufficient workspace."
    }
   ]
  },
  {
   "title": "ESI parse errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(varnish_main_esi_errors{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "ESI parse errors (unlock)"
    },
    {
     "expr": "rate(varnish_main_esi_warnings{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "ESI parse warnings (unlock)"
    },
    {
     "expr": "rate(varnish_main_esi_maxdepth{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "ESI hit max_esi_depth"
    },
    {
     "expr": "rate(varnish_main_esi_req_abort{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Aborted ESI subrequests"
    }
   ]
  },
  { "title": "Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by (host_name) (varnish_main_thread_live{service_name=~\"$service\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache size (objects)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "varnish_main_object_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Objects evicted or expired",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(varnish_main_lru_nuked{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Number of LRU nuked objects"
    },
    {
     "expr": "sum(rate(varnish_mse4_book_liberated{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Number of objects evicted to gain free book slots"
    },
    {
     "expr": "sum(rate(varnish_mse4_store_pruned_objects{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Number of objects evicted during segment pruning"
    },
    {
     "expr": "sum(rate(varnish_main_expired{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Expired objects"
    }
   ]
  },
  {
   "title": "Cache size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (label_replace(\n  label_replace(\n    label_replace({__name__=~\"varnish_sma_.*_g_bytes\"}, \"storage_space\", \"used\", \"unsused\", \".*\"),\n    \"storage_name\",\n    \"$name\",\n    \"__name__\",\n    \"varnish_sma_(?P<name>.*)_g_.*\"\n  ),\n  \"__name__\",\n  \"varnish_storage_bytes\",\n  \"unused\",\n  \".*\"\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Client Response TTLB",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(increase(varnish_client_duration_total_seconds_bucket{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Backend Response TTLB",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum(increase(varnish_backend_duration_total_seconds_bucket{service_name=~\"$service\",instance=~\"$instance\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}