include:
  - compose-common.yaml

services:
  varnish:
    image: varnish
    profiles: [varnish]
    volumes:
      - workdir:/var/lib/varnish
      - ./conf/default.vcl:/etc/varnish/default.vcl
    ports:
      - "8080:80"
    depends_on:
      origin-files:
        condition: service_started
      origin-esi:
        condition: service_started

  varnish-otel:
    image: varnish
    profiles: [varnish]
    command: varnish-otel
    volumes:
      - workdir:/var/lib/varnish
    depends_on:
      - varnish
    environment:
      OTEL_RESOURCE_ATTRIBUTES: service.instance.id=varnish1
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_SERVICE_NAME: varnish
      OTEL_VARNISH_WORKDIR: varnishd
    build:
      dockerfile_inline: |
        FROM varnish
        USER root
        RUN set -ex; \
            apt-get update; \
            apt-get install -y varnish-otel; \
            rm -rf /var/lib/apt/lists/*
        USER varnish

volumes:
  workdir:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
