services:
  load_generator:
    image: curlimages/curl
    profiles: [varnish]
    volumes:
      - ./src/load_generator.sh:/usr/bin/load_generator
    command: /usr/bin/load_generator
    depends_on:
      - varnish

  origin-files: &origin
    command: /app/main origin-files
    profiles: [varnish]
    volumes:
      - ./data:/orig_data
    environment: &otel_env
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
    build:
      dockerfile_inline: |
        FROM golang
        WORKDIR /app/
        COPY src/origin/ .
        RUN set -ex; \
            go env -w GOPROXY=direct; \
            CGO_ENABLED=0 go build -o /app/main main.go

  origin-esi:
    <<: *origin
    command: /app/main origin-esi

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.116.1
    container_name: otel-collector
    command: ["--config=/etc/otelcol/otel-collector.yaml"]
    volumes:
      - ./conf/otel-collector.yaml:/etc/otelcol/otel-collector.yaml:ro
    ports:
      - "4318:4318" # OTLP HTTP receiver (exposed to host)
      - "4317:4317" # OTLP gRPC receiver (also exposed for convenience)
      - "8888:8888" # Collector self-metrics
    depends_on:
      - loki
      - prometheus
      - tempo

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    volumes:
      - ./conf/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./conf/grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    depends_on:
      - loki
      - prometheus
      - tempo

  tempo:
    image: grafana/tempo
    container_name: tempo
    command: -config.file=/etc/tempo/tempo.yaml
    volumes:
      - ./conf/tempo.yaml:/etc/tempo/tempo.yaml:ro
    ports:
      - "3200:3200"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --web.enable-otlp-receiver
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
    volumes:
      - ./conf/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"

