services:
  origin:
    image: python
    volumes:
      - ./data:/orig_data
    command:
      - python
      - -m
      - http.server
      - --directory
      - /orig_data
      - "80"
    stop_grace_period: 1s

  cache:
    image: quay.io/varnish-software/varnish-plus:latest
    deploy:
      replicas: 10
    volumes:
      - ./conf/default-cache.vcl:/etc/varnish/default.vcl

  lb:
    image: quay.io/varnish-software/varnish-plus:latest
    volumes:
      - ./conf/default-lb.vcl:/etc/varnish/default.vcl
    ports:
      - 8080:6081
